version: "3.7"

services: 
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        container_name: phpmyadmin_test
        ports: 
            - "3310:80"
        environment: 
            PMA_HOSTS: mysql
        depends_on: 
            - mysql
            - redis
            - redisCommander

    mysql:
        image: mysql:latest
        container_name: mysql_test
        ports: 
            - "3306:3306"
        environment: 
            MYSQL_DATABASE: gamer888
            MYSQL_ROOT_PASSWORD: password
            MYSQL_USER: apple
            MYSQL_PASSWORD: google

    redis:
        image: redis:5.0.7-alpine
        container_name: redis_test
        ports: 
            - "6379:6379"
        # environment:
        #     - REDIS_PASSWORD=my_password

    golang:
        image: golang:1.13.7-alpine3.11
        container_name: golang_test
        volumes: 
            - .:/go/src/go-with-compose
        working_dir: /go/src/go-with-compose
        command: go run main.go
        # restart: always
        ports: 
            - "8080:8080"
        # depends_on:
        #     - mysql
        #     - redis
        #     - phpmyadmin

    redisCommander:
        image: rediscommander/redis-commander:latest
        container_name: redisCommander_test
        ports: 
            - "8081:8081"
        environment: 
            - REDIS_HOSTS=local:redis:6379
        depends_on: 
            - redis